### ISSUE TITLE
TypeError: unsupported operand type(s) for *

### ISSUE THREAD

**Issue by alchemicsoundscape** [theFroh/imagepacker#6]
I thought since the code was last commited 1 year ago that this would be a useless endeavor that I happened to stumble upon, but since you responded quite recently to an issue, I figured I could probably get on here and ask about the issue I'm having. I've been fumbling for hours trying to get this to work since I'm no Python coder. but I've finally arrived at this error before the command window closes out. Seems like something definitely out of my hands... any ideas what causes this?

![ss1](https://user-images.githubusercontent.com/42986668/45065600-0960d700-b06f-11e8-98f8-0aef4df02618.png)

**Comment by theFroh** [comment]
Hey, that looks like it is choking on two textures being referenced but not used at all (no UV coordinates).

Could you try importing your OBJ into Blender, confirming the textures you expect appear in there, and then after exporting, attempt to use the script on the result? That is, if you've not already implicitly done this by exporting from Blender already!

Is that actually where your image files are stored? `C:\Python36\*...*.png`

That appears very much to be as if its looking in the "current working directory" for the files, and is hopelessly trying to read them from the Python installation directory. 

If that's the case, option 1. is to open your command prompt in the correct directory first. Easiest way to do that in Windows 10 is to browse to the folder with your model and textures and go to the "File" menu to launch an instance of PowerShell:

![Image of PowerShell access via Windows File Explorer](https://i.imgur.com/7MsMbT6.png)

Then, with your newly launched PowerShell,
1. Type `py ` (note the space), 
2. Drag and drop the Python script onto the PowerShell window -- that should fill in the next part, giving you `py /path/to/script.py` 
3. Type another space, and then drag and drop your OBJ file onto the PowerShell window, leaving you with `py /path/to/script.py /path/to/obj.obj` (or alternatively, if you've opened PowerShell in the same folder as your OBJ file, just start typing the name of the file and press TAB to auto-complete it).

If you have any issues with that, a hacky option 2. is to move your texture files into where it is looking. That'd be `C:\Python36\`.

Let me know if you hit any snags or have any success!

**Comment by alchemicsoundscape** [comment]
Hey, thanks for such a quick reply. It is in the right directory, since I wanted to keep things simple and in the same place as I was trial-and-erroring this process (but also because I didn't know how to do what you just explained haha). I did try to go through your directions so we were on the same page, but the PowerShell window won't accept drag and drop operations. I tried googling it to see if I could fix that myself before coming back for assistance, but I'm just not familiar enough with the jargon to figure it out on my own. Like I said, I'm a complete newb so I've been diligent but it is very frustrating getting stuck at every step and having to google the answers...

In any case, I think I found the main issue that I'm seeing with the models. The UV maps are just... all wrong. They are not laying on the models correctly at all... and these are exported right from WoW model viewer. I didn't mess with them at all.

![door in blender](https://user-images.githubusercontent.com/42986668/45118042-15e73d00-b10c-11e8-807d-b6f2874787d2.png)

I tried out my deathwing.obj just to see what would happen, and to put it kindly... it's a hot damn mess.

![deathwing in blender](https://user-images.githubusercontent.com/42986668/45118378-31067c80-b10d-11e8-8f61-fa25f0c610f9.png)
![deathwing in blender 2](https://user-images.githubusercontent.com/42986668/45118382-34016d00-b10d-11e8-9379-642905e987b6.png)

These are unmodified from WoW model viewer, and I feel like this might be the source of my problems. Am I doing something wrong with exporting? Have you experienced this before?

**Comment by alchemicsoundscape** [comment]
An update as I've come back to play around with this. Not all models run into this issue. Simpler ones like pets convert just fine, and I've even tried a saved player character with many separate texture files. Those were all compiled successfully and I have actually been able to get some _packed results.

What is not consistent is which models seem to export correctly, without compiling the UV maps onto one clusterf$&k and calling it a clear and clean UV map... I've tried some other models that display the textures incorrectly, and as expected, none of those work. I can only assume that this an internal problem from WoW model viewer's side. The thing is that I have searched google for anyone having similar issues to this and have come up with absolutely nothing. I might submit a report to Jeromnimo about it, but I wouldn't know how to describe how to replicate it since I'm (seemingly) the only one with the issue? What are your thoughts?

**Comment by theFroh** [comment]
Honestly those UV's look like they're for the wrong texture if anything. Does the model viewer export direct to .OBJ or is there some other intermediary format? If it exports direct, can you throw an example (model + material + textures) into a .ZIP so I can have a squizz?

As for reporting it to him, if you're exporting an OBJ out of the viewer, and then importing them into Blender like that, I would explain exactly that, and show what you are seeing. Assuming it isn't just a wrong-texture-to-UVs issue that flipping through the textures in Blender doesn't resolve.

**Comment by alchemicsoundscape** [comment]
For sure, I'll give you an obj + mtl + png zip to take a look at.

[Deathwing Idle.zip](https://github.com/theFroh/imagepacker/files/2355514/Deathwing.Idle.zip)

**Comment by alchemicsoundscape** [comment]
Yeah, it's produced by doing a simple File > Export Model > OBJ... where I am prompted to name it and voila. Here's the log from WMV:

> INFO	| 2018-09-05 22:17:58.946	| Exporting creature/deathwing/deathwing.m2 in "C:\\Users\\Celestino Jones\\Documents\\WoW 5e tokens\\deathwing idle.obj"
> INFO	| 2018-09-05 22:17:58.946	| Exporting creature/deathwing/deathwing.m2 materials in "C:/Users/Celestino Jones/Documents/WoW 5e tokens/deathwing idle.mtl"
> INFO	| 2018-09-05 22:17:58.947	| Using Verticies
> INFO	| 2018-09-05 22:17:59.228	| nb textures to export : 3
> INFO	| 2018-09-05 22:17:59.228	| Exporting GL texture with id  7 in C:/Users/Celestino Jones/Documents/WoW 5e tokens\deathwing idle_deathwing1.png
> INFO	| 2018-09-05 22:17:59.402	| Exporting GL texture with id  5 in C:/Users/Celestino Jones/Documents/WoW 5e tokens\deathwing idle_deathwing2.png
> INFO	| 2018-09-05 22:17:59.555	| Exporting GL texture with id  1 in C:/Users/Celestino Jones/Documents/WoW 5e tokens\deathwing idle_deathwing3.png

btw I closed the program out before I copied the log so I just duplicated the process and checked that it had the same results as before in blender before sharing it.

**Comment by theFroh** [comment]
Sorry about the delay; busy week.

Mmm definitely on WMV here. 
Below is the MTL file that you sent; it isn't that long and is fairly straightforward to understand. 

Basically, the `newmtl xxx` indicates the start of a material (and in this case, texture) section, with `xxx` being the name being given for that material. The rest of the lines (`Kd ...` and so on) until the next `newmtl xxx` are just defining the material's properties, with `map_Kd xxx` defining the material's texture (diffuse texture; colour).

The reason something is clearly off here is that _all of the materials defined here_ have the same name. Look at the `newmtl xxx` lines -- they are all calling the material `creature/deathwing/deathwing.m2_Geoset_000`.

This means each one is replacing the one before it, so in effect, only the very last one in this file is doing anything, which is one that uses the texture file `deathwing idle_deathwing1.png`. So, everything in the OBJ itself (as seen in Blender) would be using that single texture file, which I can only assume is the head/neck/upper torso of the dragon as they appear fine.

So, my recommendation is to see if you can't export as a different format (Blender can handle a lot of formats!) and then export from Blender as OBJ, and then try packing that output. You should know at the point of import into Blender whether the other format/s that WMV can produce are similarly affected or not.

If it is still jank coming out of WMV, I'd raise an issue with the bloke running the show there for sure.

```
#
# mtl file for deathwing idle.obj obj file
#

newmtl creature/deathwing/deathwing.m2_Geoset_000
illum 2
Kd 1.000000 1.000000 1.000000
Ka 0.250000 0.250000 0.250000
Ks 0.000000 0.000000 0.000000
Ke 0.000000 0.000000 0.000000
Ns 0.000000
map_Kd deathwing idle_deathwing3.png
newmtl creature/deathwing/deathwing.m2_Geoset_000
illum 2
Kd 1.000000 1.000000 1.000000
Ka 0.250000 0.250000 0.250000
Ks 0.000000 0.000000 0.000000
Ke 0.000000 0.000000 0.000000
Ns 0.000000
map_Kd deathwing idle_deathwing2.png
newmtl creature/deathwing/deathwing.m2_Geoset_000
illum 2
Kd 1.000000 1.000000 1.000000
Ka 0.250000 0.250000 0.250000
Ks 0.000000 0.000000 0.000000
Ke 0.000000 0.000000 0.000000
Ns 0.000000
map_Kd deathwing idle_deathwing1.png
newmtl creature/deathwing/deathwing.m2_Geoset_000
illum 2
Kd 1.000000 1.000000 1.000000
Ka 0.250000 0.250000 0.250000
Ks 0.000000 0.000000 0.000000
Ke 0.000000 0.000000 0.000000
Ns 0.000000
map_Kd deathwing idle_deathwing3.png
newmtl creature/deathwing/deathwing.m2_Geoset_000
illum 2
Kd 1.000000 1.000000 1.000000
Ka 0.250000 0.250000 0.250000
Ks 0.000000 0.000000 0.000000
Ke 0.000000 0.000000 0.000000
Ns 0.000000
map_Kd deathwing idle_deathwing2.png
newmtl creature/deathwing/deathwing.m2_Geoset_000
illum 2
Kd 1.000000 1.000000 1.000000
Ka 0.250000 0.250000 0.250000
Ks 0.000000 0.000000 0.000000
Ke 0.000000 0.000000 0.000000
Ns 0.000000
map_Kd deathwing idle_deathwing2.png
newmtl creature/deathwing/deathwing.m2_Geoset_000
illum 2
Kd 1.000000 1.000000 1.000000
Ka 0.250000 0.250000 0.250000
Ks 0.000000 0.000000 0.000000
Ke 0.000000 0.000000 0.000000
Ns 0.000000
map_Kd deathwing idle_deathwing3.png
newmtl creature/deathwing/deathwing.m2_Geoset_000
illum 2
Kd 1.000000 1.000000 1.000000
Ka 0.250000 0.250000 0.250000
Ks 0.000000 0.000000 0.000000
Ke 0.000000 0.000000 0.000000
Ns 0.000000
map_Kd deathwing idle_deathwing1.png
```

**Comment by theFroh** [comment]
Yeah, here's the last referenced texture, and it looks like the one containing the face to me:

![Deathwing Head/Torso Texture](https://user-images.githubusercontent.com/2473822/45239954-9fb82580-b319-11e8-8861-1fa116833837.png)

And what I see in Blender for reference...
![untitled](https://user-images.githubusercontent.com/2473822/45240110-12290580-b31a-11e8-9019-e48ad93f4988.jpg)

**Comment by alchemicsoundscape** [comment]
No worries, I've been busy too. Thanks for all your help so far. It's nice to know that it isn't a user error here haha. 

The only options I have to export models out of WMV other than OBJ is Modelinfo.xml (which doesn't seem to do anything when clicked on) and FBX, neither of which seem to produce the same result as an OBJ. Are there other ways to export from WMV that I'm not aware of?

**Comment by theFroh** [comment]
You can also manually fix this by doing the following:
1. Open the .OBJ up and slap a number onto the end of each `usemtl xxx` line (every `usemtl` line is identical, this is exactly the issue!). So, for example, `usemtl creature/deathwing/deathwing.m2_Geoset_000` can become `usemtl creature/deathwing/deathwing.m2_Geoset_000_1` -- increase that number with each one you find; there are only 8 in the deathwing model.
2. Import that OBJ into Blender; there will not be any textures, but after selecting the object you should see your eight materials in the materials tab rather than just one (see my attached picture for what happens if you give each a colour).
3. Select the first material, go to the texture tab and click the texture dropdown, you should see the 8 or so `kd.00x` textures that have come in from the MTL. Even though there are 8 listed, there are actually only three unique textures (3 PNGs); the MTL has repeated the exact same chunk multiple times for each, that's all. The last `kd.00x` texture is the last material in the MTL, which is `idle_deathwing1.png` -- the second last is `idle_deathwing3.png` and the third last is `deathwing idle_deathwing2.png` -- that's all three textures, so you should only need those bottom 3 `kd.00x` textures for the next steps.
4. Pick a texture, you should see it apply somewhere on the model immediately. If it is correct, good! If it isn't, pick another (again, you should only need to go through the bottom three textures).
5. Once you have the right texture for this material, pick the next material. Repeat step 4 and 5 until you have done each of the 8 materials.
6. Congratulations, you've corrected the object's texture mapping, and should be able to export as an OBJ from Blender for consumption in my script.

![fancy dargon](https://user-images.githubusercontent.com/2473822/45242059-418f4080-b321-11e8-8421-18a6f4e3804b.jpg)

**Comment by theFroh** [comment]
Just saw your response. FBX is a viable option, try importing one of them into Blender and check if its textures are also all janky. Otherwise your best bet is to manually re-assign the textures as per my last message.

**Comment by alchemicsoundscape** [comment]
Awesome! It works! Through some dumb luck and experimentation (but mostly dumb luck), I was actually able to skip the in-program manual steps in the MTL file by doing the same exact thing as done in the OBJ file. After hitting save and importing the model, it automatically (and correctly) assigns the textures! 

it feels great finally seeing the boy in the game... there he is!
![deathwing](https://user-images.githubusercontent.com/42986668/45244502-f3405a00-b2ac-11e8-92b5-e9365e779cd0.png)

Now, there's something strange going on with some transparencies and spotted-looking areas (the chin notably), but I'll take what I can get at this point and continue to troubleshoot in Blender, cause I'm sure that's where the discrepancy is since I am not familiar with 3d model programs either. But if you know the quick fix because I missed a checkbox or value somewhere I'm all ears. Otherwise thanks a ton!! I really appreciate it, and I'm excited to flood the workshop with WoW models haha.
